### ISSUE TITLE
AS2WASM Build Error

### ISSUE THREAD

**Issue by kennylerma** [apache/royale-asjs#106]
@erikdebruin I'm attempting to build AS2WASM feature branch.  However, I have some issues.  The package.json are incorrect.  The script commands should be separated with "&&" instead of ";"  Additionally, information on a windows build would be helpful in the documentation.

I have successfully built everything but an actual wasm build output.  When I attempt to build the test project, I get a JNI error.  Do I need a specific version of JAVA?  I'm really interested in what you have created but the wastc.jar doesn't seem to work maybe?  I'm just not sure what I'm missing.

stderr: Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/royale/compiler/problems/ICompilerProblem
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: org.apache.royale.compiler.problems.ICompilerProblem
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more

exec error: Error: Command failed: /usr/bin/java -Xmx384m -Dsun.io.useCanonCaches=false -jar "lib/compiler/wastc.jar" -external-library-path="lib/player/playerglobal.swc" src/wasmtest.as
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/royale/compiler/problems/ICompilerProblem
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: org.apache.royale.compiler.problems.ICompilerProblem
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more

**Comment by kennylerma** [comment]
@erikdebruin @aharui Any idea why I'm getting the missing class for ICompilerPromblem?

**Comment by aharui** [comment]
The build script may be out-of-date.  ICompilerProblem is in compiler-common.jar in recent branches.

**Comment by kennylerma** [comment]
Thanks @aharui.  I think that may point me in right direction.  I unzipped the wastc.jar and it is indeed missing classes, so something in the build script is incorrect.  I'll see if I can figure it out.

Thanks

**Comment by kennylerma** [comment]
Well, I got it to run without errors, but unfortunately no output in the bin folder :(

```
Set arg 'src' to 'src/wasmtest.as'
WASTC
-external-library-path=lib/player/playerglobal.swc
src/wasmtest.as
0.688373382 seconds
```

**Comment by kennylerma** [comment]
@aharui I'm doing my best to work through the compiler code, but so far I'm getting "Missing builtin type Object" when CompilerProject.getFatalProblems() is called.  Not sure how these built in types get provided for a project.  Any help is appreciated.

**Comment by aharui** [comment]
@kennylerma I did not work on this WASM stuff at all so I have less of a clue than you do at this point.  I'm buried with other tasks as well.  The best I can do is quickly answer simple questions.  If you want to take the lead on making it work, that would be awesome.

So, regarding "Missing builtin type Object", for JS and SWF output, that means that a SWC that defines Object has not been specified/loaded by the compiler.  In Royale for JS, we use js.swc from the royale-typedefs repo on the external-library-path.  For SWF, we use playerglobal.swc or airglobal.swc on the external-library-path.
