### ISSUE TITLE
Having <mx:Repeater /> causes compiler Error: Unable to resolve resource bundle 'core'

### ISSUE THREAD

**Issue by dhendargo1** [apache/royale-asjs#1095]
Hi,
Below is content of a .mxml file that reliably (100% of the time) reproduces this issue.
Thanks for looking into this and let me know if you need further info.
-Danny

`<?xml version="1.0" encoding="utf-8"?>

<mx:Application
    xmlns:mx="library://ns.apache.org/royale/mx"
>
	<mx:Label text="If you see this on screen, the issue has been resolved." x="10" y="10"/>
	<mx:Repeater />		
</mx:Application>`

**Comment by dhendargo1** [comment]
I forgot to mention that I was using Royale lib: 0.9.8 on Windows 10.

**Comment by dhendargo1** [comment]
Update: using build 3047, I am getting the following stack trace:
`src/RepeaterBug.mxml
c:\development\royale-bugs\RepeaterBug\src\RepeaterBug.mxml line 9 column 1 Error: Internal error in ASBlockWalker subsystem, when generating code for: c:\development\royale-bugs\RepeaterBug\src\RepeaterBug.mxml line 9 column 1: java.lang.IllegalArgumentException: No handler specified for nodes of type 'MXMLRepeater'
        at org.apache.royale.compiler.internal.visitor.mxml.MXMLNodeSwitch.handle(MXMLNodeSwitch.java:200)
        at org.apache.royale.compiler.internal.codegen.mxml.MXMLBlockWalker.walk(MXMLBlockWalker.java:156)
        at org.apache.royale.compiler.internal.codegen.mxml.royale.MXMLRoyaleEmitter.emitArray(MXMLRoyaleEmitter.java:3174)
        at org.apache.royale.compiler.internal.codegen.mxml.MXMLBlockWalker.visitArray(MXMLBlockWalker.java:305)
        at org.apache.royale.compiler.internal.visitor.mxml.MXMLNodeSwitch.handle(MXMLNodeSwitch.java:77)
        at org.apache.royale.compiler.internal.codegen.mxml.MXMLBlockWalker.walk(MXMLBlockWalker.java:156)
        at org.apache.royale.compiler.internal.codegen.mxml.royale.MXMLRoyaleEmitter.emitPropertySpecifier(MXMLRoyaleEmitter.java:3086)
        at org.apache.royale.compiler.internal.codegen.mxml.MXMLBlockWalker.visitPropertySpecifier(MXMLBlockWalker.java:273)
        at org.apache.royale.compiler.internal.visitor.mxml.MXMLNodeSwitch.handle(MXMLNodeSwitch.java:111)
        at org.apache.royale.compiler.internal.codegen.mxml.MXMLBlockWalker.walk(MXMLBlockWalker.java:156)
        at org.apache.royale.compiler.internal.codegen.mxml.royale.MXMLRoyaleEmitter.emitDocument(MXMLRoyaleEmitter.java:877)
        at org.apache.royale.compiler.internal.codegen.mxml.royale.MXMLRoyaleBlockWalker.visitDocument(MXMLRoyaleBlockWalker.java:69)
        at org.apache.royale.compiler.internal.visitor.mxml.MXMLNodeSwitch.handle(MXMLNodeSwitch.java:89)
        at org.apache.royale.compiler.internal.codegen.mxml.MXMLBlockWalker.walk(MXMLBlockWalker.java:156)
        at org.apache.royale.compiler.internal.codegen.mxml.royale.MXMLRoyaleBlockWalker.visitFile(MXMLRoyaleBlockWalker.java:61)
        at org.apache.royale.compiler.internal.visitor.mxml.MXMLNodeSwitch.handle(MXMLNodeSwitch.java:95)
        at org.apache.royale.compiler.internal.codegen.mxml.MXMLBlockWalker.walk(MXMLBlockWalker.java:156)
        at org.apache.royale.compiler.internal.codegen.mxml.MXMLBlockWalker.visitCompilationUnit(MXMLBlockWalker.java:187)
        at org.apache.royale.compiler.internal.codegen.mxml.MXMLWriter.writeTo(MXMLWriter.java:69)
        at org.apache.royale.compiler.clients.MXMLJSCRoyale.compile(MXMLJSCRoyale.java:411)
        at org.apache.royale.compiler.clients.MXMLJSCRoyale._mainNoExit(MXMLJSCRoyale.java:259)
        at org.apache.royale.compiler.clients.MXMLJSCRoyale.mainNoExit(MXMLJSCRoyale.java:216)
        at org.apache.royale.compiler.clients.MXMLJSC._mainNoExit(MXMLJSC.java:363)
        at org.apache.royale.compiler.clients.MXMLJSC.mainNoExit(MXMLJSC.java:298)
        at org.apache.royale.compiler.clients.MXMLJSC.staticMainNoExit(MXMLJSC.java:256)
        at org.apache.royale.compiler.clients.MXMLJSC.main(MXMLJSC.java:238)
`

**Comment by yishayw** [comment]
Thanks for reporting this. mx:Repeater is not implemented. I would suggest to rewrite that part of your code for now.
________________________________
