### ISSUE TITLE
SimpleTable issue

### ISSUE THREAD

**Issue by LudvikWiejowski** [apache/royale-asjs#418]
Hi,

simpletable is not working to me, maybe I'm doing something wrong.

<?xml version="1.0" encoding="UTF-8"?>

<j:Application xmlns:fx="http://ns.adobe.com/mxml/2009"
              xmlns:j="library://ns.apache.org/royale/jewel"
              xmlns:js="library://ns.apache.org/royale/basic"
              xmlns:html="library://ns.apache.org/royale/html">
    

    <j:initialView>
        <j:View id="view">
            <j:states>
                <js:State name="login" />        
                <js:State name="loggedIn" />        
            </j:states>
            
            <j:beads>
                <js:SimpleStatesImpl/>
            </j:beads>

            <j:Card id="loginForm" includeIn="login">
                <html:H1 text="Royale login"/>
                <j:TextInput id="username" text="someuser"/>
                <j:TextInput id="password" text="somepass">
                    <j:beads>
                        <j:PasswordInput/>
                    </j:beads>
                </j:TextInput>
                <j:Button text="Login" emphasis="primary" click="view.currentState = 'loggedIn'" />
            </j:Card>

            <j:Card id="loggedInForm" includeIn="loggedIn">
                <html:H1 text="You are logged in!! :)"/>
                <j:Button text="Logout" click="view.currentState = 'login'"/>

                <j:SimpleTable>
					<j:THead>
						<j:TableRow>
							<j:TableHeaderCell width="48">
								<j:Label text="Icons" />
							</j:TableHeaderCell>
							<j:TableHeaderCell width="140">
								<j:Label text="Text Column" />
							</j:TableHeaderCell>
							<j:TableHeaderCell width="140">
								<j:Label text="Centered Text Column" />
							</j:TableHeaderCell>
							<j:TableHeaderCell>
								<j:Label text="Number Column">
									<j:beads>
										<j:TextAlign align="right"/>
									</j:beads>
								</j:Label>
							</j:TableHeaderCell>
						</j:TableRow>
					</j:THead>
					<j:TBody>
						<j:TableRow>
							<j:TableCell>
								<js:FontIcon text="ahoj"/>
							</j:TableCell>
							<j:TableCell expandRows="2">
								<j:Label text="Some text in two rows" multiline="true"/>
							</j:TableCell>
							<j:TableCell>
								<j:Label text="Some centered text">
									<j:beads>
										<j:TextAlign align="center"/>
									</j:beads>
								</j:Label>
							</j:TableCell>
							<j:TableCell>
								<j:Label text="71">
									<j:beads>
										<j:TextAlign align="right"/>
									</j:beads>
								</j:Label>
							</j:TableCell>
						</j:TableRow>
                    </j:TBody>
                </j:SimpleTable>

            </j:Card>
        </j:View>
    </j:initialView>

	<fx:Script>
		<![CDATA[
            
		]]>
	</fx:Script>
</j:Application>

Getting following error:
TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
    at org.apache.royale.jewel.supportClasses.table.TableHeaderCell.org.apache.royale.core.UIBase.addElement (/Users/luwi/VisualStudioCodeProjects/myFirstRoyale/bin/js-debug/org/apache/royale/core/UIBase.js:413:17)
    at org.apache.royale.jewel.supportClasses.table.TableHeaderCell.org.apache.royale.core.GroupBase.addElement (/Users/luwi/VisualStudioCodeProjects/myFirstRoyale/bin/js-debug/org/apache/royale/core/GroupBase.js:165:60)
    at Function.org.apache.royale.utils.MXMLDataInterpreter.initializeStrandBasedObject (/Users/luwi/VisualStudioCodeProjects/myFirstRoyale/bin/js-debug/org/apache/royale/utils/MXMLDataInterpreter.js:236:13)
    at Function.org.apache.royale.utils.MXMLDataInterpreter.generateMXMLArray (/Users/luwi/VisualStudioCodeProjects/myFirstRoyale/bin/js-debug/org/apache/royale/utils/MXMLDataInterpreter.js:125:54)
    at Function.org.apache.royale.utils.MXMLDataInterpreter.generateMXMLInstances (/Users/luwi/VisualStudioCodeProjects/myFirstRoyale/bin/js-debug/org/apache/royale/utils/MXMLDataInterpreter.js:266:50)
    at org.apache.royale.jewel.supportClasses.table.TableHeaderCell.org.apache.royale.html.Group.addedToParent (/Users/luwi/VisualStudioCodeProjects/myFirstRoyale/bin/js-debug/org/apache/royale/html/Group.js:76:50)
    at org.apache.royale.jewel.supportClasses.table.TableRow.org.apache.royale.core.UIBase.addElement (/Users/luwi/VisualStudioCodeProjects/myFirstRoyale/bin/js-debug/org/apache/royale/core/UIBase.js:414:6)
    at org.apache.royale.jewel.supportClasses.table.TableRow.org.apache.royale.core.GroupBase.addElement (/Users/luwi/VisualStudioCodeProjects/myFirstRoyale/bin/js-debug/org/apache/royale/core/GroupBase.js:165:60)
    at Function.org.apache.royale.utils.MXMLDataInterpreter.initializeStrandBasedObject (/Users/luwi/VisualStudioCodeProjects/myFirstRoyale/bin/js-debug/org/apache/royale/utils/MXMLDataInterpreter.js:236:13)
    at Function.org.apache.royale.utils.MXMLDataInterpreter.generateMXMLArray (/Users/luwi/VisualStudioCodeProjects/myFirstRoyale/bin/js-debug/org/apache/royale/utils/MXMLDataInterpreter.js:125:54)
TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
    at org.apache.royale.jewel.supportClasses.table.TableHeaderCell.org.apache.royale.core.UIBase.addElement (/Users/luwi/VisualStudioCodeProjects/myFirstRoyale/bin/js-debug/org/apache/royale/core/UIBase.js:413:17)
    at org.apache.royale.jewel.supportClasses.table.TableHeaderCell.org.apache.royale.core.GroupBase.addElement (/Users/luwi/VisualStudioCodeProjects/myFirstRoyale/bin/js-debug/org/apache/royale/core/GroupBase.js:165:60)
    at Function.org.apache.royale.utils.MXMLDataInterpreter.initializeStrandBasedObject (/Users/luwi/VisualStudioCodeProjects/myFirstRoyale/bin/js-debug/org/apache/royale/utils/MXMLDataInterpreter.js:236:13)
    at Function.org.apache.royale.utils.MXMLDataInterpreter.generateMXMLArray (/Users/luwi/VisualStudioCodeProjects/myFirstRoyale/bin/js-debug/org/apache/royale/utils/MXMLDataInterpreter.js:125:54)
    at Function.org.apache.royale.utils.MXMLDataInterpreter.generateMXMLInstances (/Users/luwi/VisualStudioCodeProjects/myFirstRoyale/bin/js-debug/org/apache/royale/utils/MXMLDataInterpreter.js:266:50)
    at org.apache.royale.jewel.supportClasses.table.TableHeaderCell.org.apache.royale.html.Group.addedToParent (/Users/luwi/VisualStudioCodeProjects/myFirstRoyale/bin/js-debug/org/apache/royale/html/Group.js:76:50)
    at org.apache.royale.jewel.supportClasses.table.TableRow.org.apache.royale.core.UIBase.addElement (/Users/luwi/VisualStudioCodeProjects/myFirstRoyale/bin/js-debug/org/apache/royale/core/UIBase.js:414:6)
    at org.apache.royale.jewel.supportClasses.table.TableRow.org.apache.royale.core.GroupBase.addElement (/Users/luwi/VisualStudioCodeProjects/myFirstRoyale/bin/js-debug/org/apache/royale/core/GroupBase.js:165:60)
    at Function.org.apache.royale.utils.MXMLDataInterpreter.initializeStrandBasedObject (/Users/luwi/VisualStudioCodeProjects/myFirstRoyale/bin/js-debug/org/apache/royale/utils/MXMLDataInterpreter.js:236:13)
    at Function.org.apache.royale.utils.MXMLDataInterpreter.generateMXMLArray (/Users/luwi/VisualStudioCodeProjects/myFirstRoyale/bin/js-debug/org/apache/royale/utils/MXMLDataInterpreter.js:125:54)

**Comment by carlosrovira** [comment]
Hi,

I copied the code in a project, compile and test in a browser and all works ok for me. I can see the login form and pushing login see the table with one row. Can't see any problem with your code, sorry.

**Comment by piotrzarzycki21** [comment]
Could you attach full project if it's possible which you are opening and building in your IDE?

**Comment by LudvikWiejowski** [comment]
@carlosrovira thanks for confirmation, in that case I have to have some wrong setup in VSCode.
@piotrzarzycki21 attached
[myFirstRoyale.zip](https://github.com/apache/royale-asjs/files/3077684/myFirstRoyale.zip)

**Comment by carlosrovira** [comment]
Hi @LudvikWiejowski what I did is easy: I took Tour De Jewel example project and remove all code (leaving license), then copied your code and build with maven. You can take TDJ and compare with your setup to find what could be the problem

**Comment by LudvikWiejowski** [comment]
hi @carlosrovira , thanks. I also took some working example from apache royal site and put it into VSCode and it was working. Then I only included simpletable and it does not work since then. I have never done anything with Maven, but will give it a try. Thanks

**Comment by carlosrovira** [comment]
Thanks, let us know if you found where is the problem and if you get all working. In that case you can close this ticket yourself. Thanks

**Comment by piotrzarzycki21** [comment]
Hey @LudvikWiejowski I just took your attached project and fixed your asconfig. I have configured project both for VSCode and Moonshine. Take a look what I have added to understand what you missed in the project. It's working fine now or at least I think so. I have used Nightly build JS only [2820](http://apacheroyaleci.westus2.cloudapp.azure.com:8080/job/royale-asjs_jsonly/2820/)

**Comment by LudvikWiejowski** [comment]
Hello @piotrzarzycki21 , thanks a lot. I replaced my project with what you sent, downloaded Nightly build JS (before I had JS and SWF), but error remains. It must be something silly on my side....
