### ISSUE TITLE
primordials is not defined during npm install

### ISSUE THREAD

**Issue by chrisvelevitch** [apache/royale-asjs#428]
I just tried installing `royale-js-swf` with
```
npm install @apache-royale/royale-js-swf -g
```
and I got the following:-
```
$ npm install @apache-royale/royale-js-swf -g
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
/usr/local/bin/asjscompc -> /usr/local/lib/node_modules/@apache-royale/royale-js-swf/royale-asjs/js/bin/asjscompcnpm
/usr/local/bin/asjsc -> /usr/local/lib/node_modules/@apache-royale/royale-js-swf/royale-asjs/js/bin/asjscnpm
/usr/local/bin/mxmlc -> /usr/local/lib/node_modules/@apache-royale/royale-js-swf/royale-asjs/js/bin/mxmlcnpm
/usr/local/bin/asnodec -> /usr/local/lib/node_modules/@apache-royale/royale-js-swf/royale-asjs/js/bin/asnodecnpm
/usr/local/bin/compc -> /usr/local/lib/node_modules/@apache-royale/royale-js-swf/royale-asjs/js/bin/compcnpm
/usr/local/bin/externc -> /usr/local/lib/node_modules/@apache-royale/royale-js-swf/royale-asjs/js/bin/externcnpm

> @apache-royale/royale-js-swf@0.9.4 postinstall /usr/local/lib/node_modules/@apache-royale/royale-js-swf
> node royale-asjs/npm/js-swf/dependencies/download_dependencies.js

fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/usr/local/lib/node_modules/@apache-royale/royale-js-swf/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/usr/local/lib/node_modules/@apache-royale/royale-js-swf/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/@apache-royale/royale-js-swf/node_modules/fstream/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @apache-royale/royale-js-swf@0.9.4 postinstall: `node royale-asjs/npm/js-swf/dependencies/download_dependencies.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @apache-royale/royale-js-swf@0.9.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/chris/.npm/_logs/2019-06-28T07_32_29_548Z-debug.log
```
and I have attached the log file.

Is this a known issue?

Env: MacOS 11.13.6, npm@6.9.2, node@v12.3.1

[2019-06-28T07_32_29_548Z-debug.log](https://github.com/apache/royale-asjs/files/3338071/2019-06-28T07_32_29_548Z-debug.log)

**Comment by joshtynjala** [comment]
Based on some Google searching, this seems to be caused by a breaking change to an internal API in Node.js 12. One of the dependencies in the npm version of Royale seems to rely on an older version of the graceful-fs module that (incorrectly) used this internal API. If the Royale team upgrades these dependencies in the npm version of Royale, that should fix this issue.

Possible temporary workarounds:

* Downgrade to an older version of Node.js.
* Download Royale from here instead: https://royale.apache.org/download/

**Comment by bigosmallm** [comment]
I will try to update the dependencies and see if I can get this to work properly.

**Comment by joshtynjala** [comment]
Thanks, @bigosmallm! If you have time, it looks like #450 also affects npm installation (for royale-js-swf).

**Comment by bigosmallm** [comment]
Please test the beta and provide feedback.  

Steps:
`
npm uninstall @apache-royale/royale-js-swf -g (in case you already have it installed)
npm i @apache-royale/royale-js-swf@0.9.6-beta0 -g

Test with the CLI:
npm i @apache-royale/cli -g
`

Documentation for CLI tool here: https://www.npmjs.com/package/@apache-royale/cli
