### ISSUE TITLE
installing Royale-js-swf via NPM: playerglobal25_0.swc Download failed with status code: 404

### ISSUE THREAD

**Issue by yozef** [apache/royale-asjs#450]
While npm installing royale-js-swf on Mac: `sudo npm install @apache-royale/royale-js-swf -g`

```
This license is not compatible with the Apache v2 license.
Do you want to download and install the playerglobal.swc?
This is a required component (y/n):  y
Downloading playerglobal.swc from http://download.macromedia.com/get/flashplayer/updaters/25/playerglobal25_0.swc
Downloading: http://download.macromedia.com/get/flashplayer/updaters/25/playerglobal25_0.swc
Download failed with status code: 404
```

**Comment by yozef** [comment]
Further investigation:
```
"org_apache_royale": {
    "flash_player_global_url": "http://download.macromedia.com/get/flashplayer/updaters/25/",
    "flash_player_global_file_name": "playerglobal25_0.swc",
    "adobe_air_url": "http://airdownload.adobe.com/air/win/download/25.0/",
    "adobe_air_file_name": "AdobeAIRSDK.zip",
    "player_version": "25.0",
    "swf_version": "36",
    "swf_object_url": "http://github.com/swfobject/swfobject/archive/",
    "swf_object_file_name": "2.2.zip",
    "flatui_url": "https://github.com/designmodo/Flat-UI/archive/",
    "flatui_file_name": "2.2.2.zip"
  },
```

None of the URLs resolve to a file.

http://download.macromedia.com/get/flashplayer/updaters/25/playerglobal25_0.swc -- Not Found.

**Comment by aharui** [comment]
Thanks for reporting and investigating.  The urls moved and we'll need to update that in the next release.  If you don't need SWF output, try the royale-js package instead of the royale-js-swf package.

**Comment by yozef** [comment]
Alright - Thanks Alex! 
_Good to see your nickname by the way, after such long years :)_ 
Hope this project brings back all the fine devs from the AS3 world.

**Comment by bigosmallm** [comment]
@aharui can you please list the correct urls?

**Comment by aharui** [comment]
I did attempt to update them in b56c1c20397797a0cd29763f6b6908d21d2fcbfb.
Is there still an issue?

**Comment by bigosmallm** [comment]
Ah I dint realize that you had updated the urls.  I will test it via the 0.9.6-beta release.

**Comment by bigosmallm** [comment]
Please test the beta and provide feedback.  

Steps:
```
npm uninstall @apache-royale/royale-js-swf -g (in case you already have it installed)
npm i @apache-royale/royale-js-swf@0.9.6-beta0 -g

Test with the CLI:
npm i @apache-royale/cli -g
```

Documentation for CLI tool here: https://www.npmjs.com/package/@apache-royale/cli

**Comment by Harbs** [comment]
@yozef Is this resolved?

**Comment by carlosrovira** [comment]
Hi Harbs, I think NPM is actually failing. This is my log:

```
/usr/local/bin/npx -> /usr/local/lib/node_modules/npm/bin/npx-cli.js
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
+ npm@6.12.0
added 1 package from 1 contributor, removed 1 package and updated 11 packages in 4.275s
macbookpro:royale-compiler carlosrovira$ npm uninstall @apache-royale/royale-js-swf -g
up to date in 0.03s
macbookpro:royale-compiler carlosrovira$ npm i @apache-royale/royale-js-swf@0.9.6-beta0 -g
/usr/local/bin/mxmlc -> /usr/local/lib/node_modules/@apache-royale/royale-js-swf/royale-asjs/js/bin/mxmlcnpm
/usr/local/bin/asjsc -> /usr/local/lib/node_modules/@apache-royale/royale-js-swf/royale-asjs/js/bin/asjscnpm
/usr/local/bin/asjscompc -> /usr/local/lib/node_modules/@apache-royale/royale-js-swf/royale-asjs/js/bin/asjscompcnpm
/usr/local/bin/compc -> /usr/local/lib/node_modules/@apache-royale/royale-js-swf/royale-asjs/js/bin/compcnpm
/usr/local/bin/asnodec -> /usr/local/lib/node_modules/@apache-royale/royale-js-swf/royale-asjs/js/bin/asnodecnpm
/usr/local/bin/externc -> /usr/local/lib/node_modules/@apache-royale/royale-js-swf/royale-asjs/js/bin/externcnpm

> @apache-royale/royale-js-swf@0.9.6-beta0 postinstall /usr/local/lib/node_modules/@apache-royale/royale-js-swf
> node dependencies/download_dependencies.js

internal/modules/cjs/loader.js:783
    throw err;
    ^

Error: Cannot find module '/usr/local/lib/node_modules/@apache-royale/royale-js-swf/dependencies/download_dependencies.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:780:15)
    at Function.Module._load (internal/modules/cjs/loader.js:685:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1014:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @apache-royale/royale-js-swf@0.9.6-beta0 postinstall: `node dependencies/download_dependencies.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @apache-royale/royale-js-swf@0.9.6-beta0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/carlosrovira/.npm/_logs/2019-10-22T13_39_41_131Z-debug.log
```

**Comment by Harbs** [comment]
Yes. I'm getting a similar error.
@bigosmallm @aharui any suggestions?

**Comment by Harbs** [comment]
I'm getting an error with the regular package too `sudo npm i @apache-royale/royale-js-swf -g`

**Comment by carlosrovira** [comment]
@Harbs finaly I get this working. I was trying with a "beta" by mistake so I did:

1.  npm uninstall @apache-royale/royale-js-swf -g
2. npm i @apache-royale/royale-js-swf@0.9.6 -g

(no sudo involved)

so I get

```
+ @apache-royale/royale-js-swf@0.9.6
added 185 packages from 116 contributors in 321.859s
```

HTH

Carlos

**Comment by carlosrovira** [comment]
So, I understand that website instructions are wrong in home and download pages. Should I update this: `npm install @apache-royale/royale-js-swf -g` to this `npm i @apache-royale/royale-js-swf@0.9.6 -g`?

And other question, is possible that `npm install @apache-royale/royale-js-swf -g` will install latest version available (in this case 0.9.6)?

Thanks

**Comment by bigosmallm** [comment]
On Tue, Oct 22, 2019, 7:12 AM Carlos Rovira <notifications@github.com>
wrote:

> So, I understand that website instructions are wrong in home and download
> pages. Should I update this: npm install @apache-royale/royale-js-swf -g
> to this npm i @apache-royale/royale-js-swf@0.9.6 -g?
>

No need for @0.9.6.  Npm downloads the latest one by default.

And other question, is possible that npm install
> @apache-royale/royale-js-swf -g will install latest version available (in
> this case 0.9.6)?
>

Yes, that is correct.

Thank you,
Om

**Comment by carlosrovira** [comment]
Thanks @bigosmallm, I could unsintall and reinstall again, and check that @0.9.6 is not needed. All worked right with `npm i @apache-royale/royale-js-swf -g`. Since this days I upgraded to Catalina, I had to update other things in my SO, but seems all is ok for me in Mac.

Don't know what could be the problem for @Harbs. If is in Windows, maybe others in that SO should try if all is ok.
