### ISSUE TITLE
Installing via NPM throws errors

### ISSUE THREAD

**Issue by yozef** [apache/royale-asjs#833]
I've been trying to install the latest release:
```
sudo npm install @apache-royale/royale-js-swf -g
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
/usr/local/bin/asjsc -> /usr/local/lib/node_modules/@apache-royale/royale-js-swf/royale-asjs/js/bin/asjscnpm
/usr/local/bin/asjscompc -> /usr/local/lib/node_modules/@apache-royale/royale-js-swf/royale-asjs/js/bin/asjscompcnpm
/usr/local/bin/mxmlc -> /usr/local/lib/node_modules/@apache-royale/royale-js-swf/royale-asjs/js/bin/mxmlcnpm
/usr/local/bin/compc -> /usr/local/lib/node_modules/@apache-royale/royale-js-swf/royale-asjs/js/bin/compcnpm
/usr/local/bin/asnodec -> /usr/local/lib/node_modules/@apache-royale/royale-js-swf/royale-asjs/js/bin/asnodecnpm
/usr/local/bin/externc -> /usr/local/lib/node_modules/@apache-royale/royale-js-swf/royale-asjs/js/bin/externcnpm

> @apache-royale/royale-js-swf@0.9.7 postinstall /usr/local/lib/node_modules/@apache-royale/royale-js-swf
> node royale-asjs/npm/js-swf/dependencies/download_dependencies.js

prompt: Apache Royale includes an optional component set
that uses fonts from designmodo.com.  The font
files are subject to and governed by the
Creative Commons Attribution-NonCommercial-NoDerivs 3.0
Unported license: http://creativecommons.org/licenses/by-nc-nd/3.0/
This license is not compatible with the Apache v2 license.
Do you want to install the designmodo fonts?
This is an optional component (y/n):  n
Skipping FlatUI installation
prompt: Apache Royale SWF support uses the Adobe Flash Player's playerglobal.swc to build Adobe Flash applications.
The playerglobal.swc file is subject to and governed by the
Adobe Flash Player License Agreement specified here:
http://wwwimages.adobe.com/content/dam/acom/en/legal/licenses-terms/pdf/Flash_Player_21_0.pdf,
By downloading, modifying, distributing, using and/or accessing the playerglobal.swc file
you agree to the terms and conditions of the applicable end user license agreement.

In addition to the Adobe license terms, you also agree to be bound by the third-party terms specified here:
http://www.adobe.com/products/eula/third_party/.
Adobe recommends that you review these third-party terms.

This license is not compatible with the Apache v2 license.
Do you want to download and install the playerglobal.swc?
This is a required component (y/n):  y
Downloading playerglobal.swc from http://fpdownload.macromedia.com/get/flashplayer/installers/archive/playerglobal/playerglobal25_0.swc
Downloading: http://fpdownload.macromedia.com/get/flashplayer/installers/archive/playerglobal/playerglobal25_0.swc
events.js:287
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open './downloads/playerglobal25_0.swc'
Emitted 'error' event on WriteStream instance at:
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at WriteStream.onerror (_stream_readable.js:729:7)
    at WriteStream.emit (events.js:310:20)
    at /usr/local/lib/node_modules/@apache-royale/royale-js-swf/node_modules/graceful-fs/graceful-fs.js:303:14
    at /usr/local/lib/node_modules/@apache-royale/royale-js-swf/node_modules/graceful-fs/graceful-fs.js:333:16
    at FSReqCallback.oncomplete (fs.js:155:23) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './downloads/playerglobal25_0.swc'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @apache-royale/royale-js-swf@0.9.7 postinstall: `node royale-asjs/npm/js-swf/dependencies/download_dependencies.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @apache-royale/royale-js-swf@0.9.7 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/FlexDev/.npm/_logs/2020-05-15T17_31_18_644Z-debug.log

**Comment by yozef** [comment]
FlatUI download URL is broken. Similarly, the playerglobal.swc file link is broken

**Comment by yozef** [comment]
I've used the following:
`npm uninstall @apache-royale/royale-js-swf -g` _to uninstall whatever got added above_
`sudo npm i @apache-royale/royale-js-swf -g`

Did the trick!
