### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined        (SingleSelectionIListModel.js:156)

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#909]
Project Details are :
https://paste.apache.org/cpo8y
Test case is available on VDI.
Go to Purchase from Select in Menu
Go to Reports -> Product Ledger in Menu
File : com/dbz/reports/view/INV/dbzProductLedger.mxml

![image](https://user-images.githubusercontent.com/42200979/92871297-3397bd00-f41e-11ea-9b72-d770979c6e3a.png)
![image](https://user-images.githubusercontent.com/42200979/92871333-3c888e80-f41e-11ea-9ffe-75599d9c4392.png)

**Comment by aharui** [comment]
Looks like dataProvider is not set.  Try adding a check to make sure dataProvider is not null in DropDownListBase

**Comment by pashminakazi** [comment]
i have added a check in DropDownListBase's get and set DataProvider
when i open dbzProductLedger the debugger goes to get DataProvider

```
if(dataProvider == null) 
   trace("dataprovider is null" + dataProvider);
}
```
![image](https://user-images.githubusercontent.com/42200979/93451611-d655ad00-f8f0-11ea-8358-890f3e21dad0.png)
![image](https://user-images.githubusercontent.com/42200979/93451628-dce42480-f8f0-11ea-8b04-91e64e11b9ef.png)

this.dataprovider
Message : maximum call stack size exceeded
Stack : "RangeError: Maximum call stack size exceeded
    at spark.components.DropDownList.spark.components.supportClasses.DropDownListBase.get__dataProvider (http://localhost:8080/SHMA/spark/components/supportClasses/DropDownListBase.js:35:88)
    at spark.components.DropDownList.spark.components.supportClasses.DropDownListBase.get__dataProvider (http://localhost:8080/SHMA/spark/components/supportClasses/DropDownListBase.js:36:12)
    at spark.components.DropDownList.spark.components.supportClasses.DropDownListBase.get__dataProvider (http://localhost:8080/SHMA/spark/components/supportClasses/DropDownListBase.js:36:12)
    at spark.components.DropDownList.spark.components.supportClasses.DropDownListBase.get__dataProvider (http://localhost:8080/SHMA/spark/components/supportClasses/DropDownListBase.js:36:12)
    at spark.components.DropDownList.spark.components.supportClasses.DropDownListBase.get__dataProvider (http://localhost:8080/SHMA/spark/components/supportClasses/DropDownListBase.js:36:12)
    at spark.components.DropDownList.spark.components.supportClasses.DropDownListBase.get__dataProvider (http://localhost:8080/SHMA/spark/components/supportClasses/DropDownListBase.js:36:12)
    at spark.components.DropDownList.spark.components.supportClasses.DropDownListBase.get__dataProvider (http://localhost:8080/SHMA/spark/components/supportClasses/DropDownListBase.js:36:12)
    at spark.components.DropDownList.spark.components.supportClasses.DropDownListBase.get__dataProvider (http://localhost:8080/SHMA/spark/components/supportClasses/DropDownListBase.js:36:12)
    at spark.components.DropDownList.spark.components.supportClasses.DropDownListBase.get__dataProvider (http://localhost:8080/SHMA/spark/components/supportClasses/DropDownListBase.js:36:12)
    at spark.components.DropDownList.spark.components.supportClasses.DropDownListBase.get__dataProvider (http://localhost:8080/SHMA/spark/components/supportClasses/DropDownListBase.js:36:12)"



value is : 
![image](https://user-images.githubusercontent.com/42200979/93452003-5419b880-f8f1-11ea-9ba8-ad69edb160fe.png)

![image](https://user-images.githubusercontent.com/42200979/93452376-c7232f00-f8f1-11ea-8834-8ee6d0e52509.png)

**Comment by aharui** [comment]
The null check should go in the selectedItems setter, not in the dataProvider getter/setters.

**Comment by pashminakazi** [comment]
same output for selectedItems setter as for dataProvider getter/setters.
maximum call stack size exceeded

**Comment by aharui** [comment]
What code did you try?  Did you use `_dataProvider` instead of `dataProvider` like the rest of the setter?
