### ISSUE TITLE
Internal error in ASBlockWalker subsystem

### ISSUE THREAD

**Issue by estanglerbm** [apache/royale-asjs#974]
When specifying an illegal fx: declaration in MXML (see attached test case), get this compiler error:

``Error: Internal error in ASBlockWalker subsystem, when generating code for:``

Full stack:

```
TestFXException.mxml line 8 column 2 Error: Internal error in ASBlockWalker subsystem, when generating code for: TestFXException.mxml line 8 column 2: java.lang.NullPointerException
        at org.apache.royale.compiler.internal.codegen.mxml.royale.MXMLRoyaleEmitter.emitInstance(MXMLRoyaleEmitter.java:2348)
        at org.apache.royale.compiler.internal.codegen.mxml.MXMLBlockWalker.visitInstance(MXMLBlockWalker.java:265)
        at org.apache.royale.compiler.internal.visitor.mxml.MXMLNodeSwitch.handle(MXMLNodeSwitch.java:101)
        at org.apache.royale.compiler.internal.codegen.mxml.MXMLBlockWalker.walk(MXMLBlockWalker.java:156)
        at org.apache.royale.compiler.internal.codegen.mxml.MXMLEmitter.emitDeclarations(MXMLEmitter.java:80)
        at org.apache.royale.compiler.internal.codegen.mxml.royale.MXMLRoyaleEmitter.emitDeclarations(MXMLRoyaleEmitter.java:829)
        at org.apache.royale.compiler.internal.codegen.mxml.MXMLBlockWalker.visitDeclarations(MXMLBlockWalker.java:217)
        at org.apache.royale.compiler.internal.visitor.mxml.MXMLNodeSwitch.handle(MXMLNodeSwitch.java:83)
        at org.apache.royale.compiler.internal.codegen.mxml.MXMLBlockWalker.walk(MXMLBlockWalker.java:156)
        at org.apache.royale.compiler.internal.codegen.mxml.royale.MXMLRoyaleEmitter.emitDocument(MXMLRoyaleEmitter.java:873)
        at org.apache.royale.compiler.internal.codegen.mxml.royale.MXMLRoyaleBlockWalker.visitDocument(MXMLRoyaleBlockWalker.java:69)
        at org.apache.royale.compiler.internal.visitor.mxml.MXMLNodeSwitch.handle(MXMLNodeSwitch.java:89)
        at org.apache.royale.compiler.internal.codegen.mxml.MXMLBlockWalker.walk(MXMLBlockWalker.java:156)
        at org.apache.royale.compiler.internal.codegen.mxml.royale.MXMLRoyaleBlockWalker.visitFile(MXMLRoyaleBlockWalker.java:61)
        at org.apache.royale.compiler.internal.visitor.mxml.MXMLNodeSwitch.handle(MXMLNodeSwitch.java:95)
        at org.apache.royale.compiler.internal.codegen.mxml.MXMLBlockWalker.walk(MXMLBlockWalker.java:156)
        at org.apache.royale.compiler.internal.codegen.mxml.MXMLBlockWalker.visitCompilationUnit(MXMLBlockWalker.java:187)
        at org.apache.royale.compiler.internal.codegen.mxml.MXMLWriter.writeTo(MXMLWriter.java:69)
        at org.apache.royale.compiler.clients.MXMLJSCRoyale.compile(MXMLJSCRoyale.java:411)
        at org.apache.royale.compiler.clients.MXMLJSCRoyale._mainNoExit(MXMLJSCRoyale.java:259)
        at org.apache.royale.compiler.clients.MXMLJSCRoyale.mainNoExit(MXMLJSCRoyale.java:216)
        at org.apache.royale.compiler.clients.MXMLJSC._mainNoExit(MXMLJSC.java:363)
        at org.apache.royale.compiler.clients.MXMLJSC.mainNoExit(MXMLJSC.java:298)
        at org.apache.royale.compiler.clients.MXMLJSC.staticMainNoExit(MXMLJSC.java:256)
        at org.apache.royale.compiler.clients.MXMLJSC.main(MXMLJSC.java:238)
```

[TestFXException.mxml.txt](https://github.com/apache/royale-asjs/files/5626611/TestFXException.mxml.txt)

**Comment by joshtynjala** [comment]
This should be fixed with commit apache/royale-compiler#c699a92f3486995124ff10dcb5750ee689a358bc
